# Generated by Django 3.1.5 on 2021-01-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
            ],
        ),
    ]
