version: 0.0
os: linux
hooks:
  BeforeInstall:
      - location: before_install
  AfterInstall:
      - location: after_install
   
  ApplicationStop:
    - location: stop_application
      timeout: 300
      runas: root
