version: 0.0
os: linux
hooks:
  BeforeInstall:
      - location: before_install.sh
  AfterInstall:
      - location: after_install.sh
   
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: root
