# Generated by Django 3.1.5 on 2021-01-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210127_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='comapany',
            new_name='name',
        ),
    ]
