# Generated by Django 3.1.5 on 2021-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210127_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
